### ISSUE TITLE
Use multithreaded Wikipedia extractor for better performance

### ISSUE THREAD

**Issue by logomancer** [conchyliculture/wikipoff-tools#5]
There is a fork of the wikipedia extractor which is multithreaded. This may give better performance when converting databases. It is available [here](https://bitbucket.org/leonardossz/multithreaded-wikipedia-extractor/wiki/Home). However, it may need to be modified to remove redirect links.

**Comment by conchyliculture** [comment]
I've been playing with the multiprocessing library and proved that starting multiple python process is negligeable in the overall converting time: "converting" processes keep waiting on the "DB inserting" thread.
